@startuml
class cz.muni.xmichalk.util.AttributeNames {
+ {static} QualifiedName ATTR_REFERENCED_BUNDLE_ID
+ {static} QualifiedName ATTR_REFERENCED_META_BUNDLE_ID
+ {static} QualifiedName ATTR_REFERENCED_BUNDLE_HASH_VALUE
+ {static} QualifiedName ATTR_HASH_ALG
+ {static} QualifiedName ATTR_PROVENANCE_SERVICE_URI
+ {static} QualifiedName ATTR_START_TIME
+ {static} QualifiedName ATTR_END_TIME
+ {static} QualifiedName ATTR_LOCATION
+ {static} QualifiedName ATTR_PROV_TYPE
+ {static} QualifiedName ATTR_LABEL
+ {static} QualifiedName ATTR_VERSION
}

class cz.muni.xmichalk.documentLoader.storageDTO.AdditionalData {
}
class cz.muni.xmichalk.querySpecification.nodeConditions.IsNotKind {
+ StatementOrBundle.Kind kind
}

class cz.muni.xmichalk.queries.GetPreferredVersion {
+ EVersionPreference versionPreference
}

class cz.muni.xmichalk.querySpecification.logicalOperations.Implication {
+ ICondition<T> premise
+ ICondition<T> consequence
}

class cz.muni.xmichalk.util.ProvJsonUtils {
}
class cz.muni.xmichalk.util.ProvDocumentUtils {
+ {static} Charset charset
}

interface cz.muni.xmichalk.querySpecification.ICondition {
}
class cz.muni.xmichalk.queries.GetConnectors {
+ Boolean backward
}

class cz.muni.xmichalk.documentLoader.storageDTO.GetMetaResponse {
+ String graph
+ Token token
}

class cz.muni.xmichalk.util.BundleNodesTraverser {
}
class cz.muni.xmichalk.querySpecification.bundleConditions.CountCondition {
+ IFindableInDocument<?> findableInDocument
+ EComparisonResult comparisonResult
+ Integer count
}

interface cz.muni.xmichalk.querySpecification.findable.IFindableInDocument {
}
interface cz.muni.xmichalk.documentLoader.IDocumentLoader {
}
enum cz.muni.xmichalk.bundleVersionPicker.EVersionPreference {
+  SPECIFIED
+  LATEST
}

class cz.muni.xmichalk.util.LinearSubgraphFinder {
}
class cz.muni.xmichalk.models.ConnectorData {
+ QualifiedNameData id
+ QualifiedNameData referencedConnectorId
+ QualifiedNameData referencedBundleId
+ QualifiedNameData referencedMetaBundleId
+ String referencedBundleHashValue
+ String provenanceServiceUri
+ String hashAlg
}

class cz.muni.xmichalk.queries.TestBundleFits {
+ ICondition<CpmDocument> condition
}

class cz.muni.xmichalk.querySpecification.logicalOperations.Either {
+ ICondition<T> first
+ ICondition<T> second
}

class cz.muni.xmichalk.queryService.BundleQueryController {
}
class cz.muni.xmichalk.querySpecification.nodeConditions.HasId {
+ String idUriRegex
}

class cz.muni.xmichalk.models.QueryParams {
+ QualifiedNameData bundleId
+ QualifiedNameData startNodeId
+ IQuery querySpecification
}

class cz.muni.xmichalk.querySpecification.subgraphConditions.edgeConditions.IsNotRelation {
+ StatementOrBundle.Kind relation
}

class cz.muni.xmichalk.querySpecification.subgraphConditions.EdgeToNodeCondition {
+ ICondition<IEdge> edgeCondition
+ ICondition<INode> nodeCondition
+ Boolean nodeIsEffect
}

class cz.muni.xmichalk.documentLoader.StorageCpmDocument {
+ CpmDocument document
+ Token token
}

class cz.muni.xmichalk.models.QualifiedNameData {
+ String nameSpaceUri
+ String localPart
}

class cz.muni.xmichalk.bundleVersionPicker.implementations.LatestVersionPicker {
}
class cz.muni.xmichalk.queries.GetNodes {
+ IFindableInDocument<INode> nodeFinder
}

class cz.muni.xmichalk.querySpecification.nodeConditions.IsKind {
+ StatementOrBundle.Kind kind
}

class cz.muni.xmichalk.querySpecification.findable.FindFittingLinearSubgraphs {
+ List<ICondition<EdgeToNode>> graphParts
}

class cz.muni.xmichalk.querySpecification.nodeConditions.HasAttr {
+ String attributeNameUri
}

class cz.muni.xmichalk.queryService.Config {
}
class cz.muni.xmichalk.bundleVersionPicker.implementations.SpecifiedVersionPicker {
}
class cz.muni.xmichalk.queries.GetNodeIds {
+ IFindableInDocument<INode> nodeFinder
}

class cz.muni.xmichalk.models.QueryResult {
+ Token token
+ JsonNode result
}

interface cz.muni.xmichalk.bundleVersionPicker.IVersionPicker {
}
class cz.muni.xmichalk.documentLoader.StorageDocument {
+ Document document
+ Token token
}

class cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrTimestampValue {
+ String attributeNameUri
+ String isEqual
+ String isBefore
+ String isAfter
}

class cz.muni.xmichalk.querySpecification.bundleConditions.AllNodes {
+ ICondition<INode> predicate
}

class cz.muni.xmichalk.models.EdgeToNode {
+ IEdge edge
+ INode node
}

class cz.muni.xmichalk.documentLoader.storageDTO.Token {
}
class cz.muni.xmichalk.queries.GetSubgraphs {
+ IFindableInDocument<List<EdgeToNode>> subgraphFinder
}

interface cz.muni.xmichalk.queries.IRequiresDocumentLoader {
}
class cz.muni.xmichalk.querySpecification.subgraphConditions.edgeConditions.IsRelation {
+ StatementOrBundle.Kind relation
}

class cz.muni.xmichalk.queryService.BundleQueryService {
}
class cz.muni.xmichalk.util.NameSpaceConstants {
+ {static} String CPM_URI
+ {static} String PROV_URI
+ {static} String BLANK_URI
+ {static} String PAV_URI
+ {static} String SCHEMA_URI
}

class cz.muni.xmichalk.documentLoader.storageDTO.TokenData {
}
enum cz.muni.xmichalk.querySpecification.bundleConditions.EComparisonResult {
+  LESS_THAN
+  LESS_THAN_OR_EQUALS
+  EQUALS
+  GREATER_THAN_OR_EQUALS
+  GREATER_THAN
}

interface cz.muni.xmichalk.queries.IQuery {
}
class cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrQualifiedNameValue {
+ String attributeNameUri
+ String uriRegex
}

class cz.muni.xmichalk.querySpecification.logicalOperations.AllTrue {
+ List<ICondition<T>> conditions
}

class cz.muni.xmichalk.util.CpmUtils {
}
class cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrLangStringValue {
+ String attributeNameUri
+ String langRegex
+ String valueRegex
}

class cz.muni.xmichalk.querySpecification.logicalOperations.AnyTrue {
+ List<ICondition<T>> conditions
}

class cz.muni.xmichalk.querySpecification.findable.FindFittingNodes {
+ ICondition<INode> nodePredicate
}

class cz.muni.xmichalk.documentLoader.storageDTO.GetDocumentResponse {
+ String document
+ Token token
}

class cz.muni.xmichalk.documentLoader.StorageDocumentLoader {
}
class cz.muni.xmichalk.Main {
}


cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.IsNotKind
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.GetPreferredVersion
cz.muni.xmichalk.queries.IRequiresDocumentLoader <|.. cz.muni.xmichalk.queries.GetPreferredVersion
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.logicalOperations.Implication
java.util.function.Predicate <|-- cz.muni.xmichalk.querySpecification.ICondition
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.GetConnectors
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.bundleConditions.CountCondition
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.TestBundleFits
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.logicalOperations.Either
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.HasId
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.subgraphConditions.edgeConditions.IsNotRelation
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.subgraphConditions.EdgeToNodeCondition
cz.muni.xmichalk.bundleVersionPicker.IVersionPicker <|.. cz.muni.xmichalk.bundleVersionPicker.implementations.LatestVersionPicker
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.GetNodes
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.IsKind
cz.muni.xmichalk.querySpecification.findable.IFindableInDocument <|.. cz.muni.xmichalk.querySpecification.findable.FindFittingLinearSubgraphs
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.HasAttr
cz.muni.xmichalk.bundleVersionPicker.IVersionPicker <|.. cz.muni.xmichalk.bundleVersionPicker.implementations.SpecifiedVersionPicker
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.GetNodeIds
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrTimestampValue
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.bundleConditions.AllNodes
cz.muni.xmichalk.queries.IQuery <|.. cz.muni.xmichalk.queries.GetSubgraphs
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.subgraphConditions.edgeConditions.IsRelation
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrQualifiedNameValue
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.logicalOperations.AllTrue
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.nodeConditions.HasAttrLangStringValue
cz.muni.xmichalk.querySpecification.ICondition <|.. cz.muni.xmichalk.querySpecification.logicalOperations.AnyTrue
cz.muni.xmichalk.querySpecification.findable.IFindableInDocument <|.. cz.muni.xmichalk.querySpecification.findable.FindFittingNodes
cz.muni.xmichalk.documentLoader.IDocumentLoader <|.. cz.muni.xmichalk.documentLoader.StorageDocumentLoader
@enduml