import base64
from base64 import b64decode
from datetime import datetime
from pathlib import Path
from unittest import TestCase

import jcs
import requests
import json

from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives._serialization import Encoding, PrivateFormat, NoEncryption
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.x509 import load_pem_x509_certificate
from prov.constants import PROV_TYPE, PROV_ATTR_BUNDLE, PROV_ATTR_SPECIFIC_ENTITY, \
    PROV_ATTR_GENERAL_ENTITY, PROV_ATTR_ACTIVITY, PROV_ATTR_ENTITY, PROV_ATTR_AGENT, PROV_ATTR_GENERATED_ENTITY, \
    PROV_ATTR_USED_ENTITY
from prov.identifier import Namespace, QualifiedName
from prov.model import ProvDocument, ProvBundle, ProvAttribution, ProvSpecialization, \
    ProvAgent, ProvActivity, ProvUsage, ProvAssociation, ProvGeneration, ProvDerivation, first, ProvInfluence, \
    ProvEntity
from prov.serializers import provjson, provn

import provenance_tests.helpers as helpers
from CPM_helpers import get_prov_generations_usages_attributions_agents
from constants import CPM_BACKWARD_CONNECTOR, CPM_FORWARD_CONNECTOR, CPM_MAIN_ACTIVITY, PAV_VERSION, PAV, \
    CPM_TRUSTED_PARTY, CPM_TOKEN, CPM_TOKEN_GENERATION, CPM, CPM_REFERENCED_META_BUNDLE_ID, CPM_REFERENCED_BUNDLE_ID, \
    CPM_REFERENCED_BUNDLE_HASH_VALUE, CPM_HASH_ALG, CPM_SENDER_AGENT, CPM_HAS_ID, CPM_ID, CPM_EXTERNAL_ID, \
    CPM_EXTERNAL_ID_TYPE
from certificate_helpers import generate_certificate, parse_certificate
from provenance_integration_tests.api_test_helpers import provenance_storage_hospital_name, fqdn_pathology, \
    provenance_storage_pathology_name, provenance_storage_hospital_name, fqdn_hospital, trusted_party_url, \
    provenance_storage_pathology_url, provenance_storage_hospital_url, create_json_for_doc_storing, TestDataCreator, \
    register_org1_to_hospital_storage, register_org_2_to_pathology_storage


class MyTestCase(TestCase):
    prov_data = TestDataCreator()


    def test_01(cls):
        cls.prov_data.org_id = "I2LAH5SF"
        register_org1_to_hospital_storage(cls.prov_data)
        json_data = create_json_for_doc_storing(cls.prov_data.doc)

        requests.post(
            f"http://{provenance_storage_hospital_url}/api/v1/organizations/I2LAH5SF/documents/test_{cls.prov_data.timestamp}_bundle",
            json.dumps(json_data))

    def test_02(self):
        # testing saving of files generated by David
        self.prov_data.org_id = "I2LAH5SF"
        with open("Dataset2_cpm_storage_v1.json", encoding="utf-8") as file:
            document = file.read()

        document_json = document.encode("utf-8")

        document_b64 = base64.b64encode(document_json)
        with open('test_sign.pem', 'rb') as file:
            private_ke = file.read()
        private_key = serialization.load_pem_private_key(private_ke, password=None)
        signature = private_key.sign(data=document_json, signature_algorithm=ec.ECDSA(hashes.SHA256()))
        json_data = {}
        json_data["document"] = document_b64.decode("utf-8")
        json_data["documentFormat"] = "json"
        json_data["signature"] = base64.b64encode(signature).decode("utf-8")
        json_data["createdOn"] = datetime.timestamp(datetime(2025, 1, 21, 2, 2, 4))

        res = requests.post(
            f"http://{provenance_storage_hospital_url}/api/v1/organizations/I2LAH5SF/documents/ProcessingBundle_V1",
            json.dumps(json_data))
        print(res.status_code)
        print(res.content.decode("utf-8"))

        self.assertTrue(False)

    def test_03(self):
        res = requests.get(
            f"http://{provenance_storage_hospital_url}/api/v1/organizations/I2LAH5SF/documents/DnaSequencingBundle_V0")
        result = json.loads(res.content)
        print(res.content)
        print(base64.b64decode(result["document"]).decode("utf-8"))
